services:
  cf:
    build:  .
    ports:
      - "80:8500"
    environment:
      - "acceptEULA=YES"
      - "password=admin"
    volumes:
      - ".:/app"
  mysql:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - "./db:/var/lib/mysql"
