services:
  cf:
    build:  .
    ports:
      - "80:8500"
    environment:
      - "acceptEULA=YES"
      - "password=admin"
    volumes:
      - ".:/app"
      - "./data:/data"
  mysql:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=error-tracking"
    volumes:
      - "./db:/var/lib/mysql"
      - "./db_init:/docker-entrypoint-initdb.d"
